# Generated by Django 5.1 on 2024-08-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=32)),
                ('nome_Completo', models.CharField(max_length=100)),
                ('data_Nasc', models.DateField()),
                ('stacks', models.TextField(blank=True)),
            ],
        ),
    ]
